name = "ElectronPropagation"
uuid = "f87e0bc7-ece5-4961-a0ec-86ec363abcc0"
authors = ["Matthias Schneller <matthias.schneller@gmail.com>"]
version = "1.0.1"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
